version: '3.9'

services:

  :rice-split-kfold:
    build:
      context: .
      dockerfile: Kfold.Dockerfile

    volumes:
      - D:/My_Data/data:/Data/Rice_Data

    # environment:
    #   # - Input_Path=/Data/Rice_Data
    #   # - Yaml_Path=/Data/Rice_Data/data.yaml
    #   # - Output_Path=/Data/Output
    #   # - Kf=2

    # command: ["python", "Train_Process.py"]

# volumes:
#   Host_Data:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: C:/Users/Aimpr/OneDrive/Desktop/My_Data4
